config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :messages
    end
  end
  resources :messages, only: [:create, :update, :destroy]
  resources :chats do
    member do
      get :members
    end
  end
  resources :chat_users, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat
  has_many :deleted_messages

  validates :content, presence: true, length: { maximum: 2000 }
  validates :user_id, presence: true
  validates :chat_id, presence: true

  def self.search_by_content(content)
    where("content LIKE ?", "%#{content}%")
  end

  # Returns chat messages that haven't been removed by current user
  def self.chat_messages_for_user(chat, user)
    message_ids = "SELECT message_id FROM deleted_messages
                    WHERE user_id = :user_id"
    where("id NOT IN (#{message_ids}) AND chat_id = :chat_id",
          user_id: user.id, chat_id: chat.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :signed_in_user
  after_action :user_activity

  def create
    message = Message.new(content: params[:message][:content],
                          user_id: params[:user_id],
                          chat_id: params[:chat_id])
    if message.save
      redirect_to message.chat
    else
      redirect_to Chat.find(params[:chat_id])
    end
  end

  def update
    message = Message.find(params[:edited_message])
    if current_user? message.user
      message.update_attribute(:content, params[:message][:content])
    end
    redirect_to message.chat
  end

  def destroy
    message = Message.find(params[:message_id])
    DeletedMessage.create(message_id: message.id, user_id: current_user.id)
    redirect_to message.chat
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<li class="message">
  <span class="user-name"><%= message.user.name %></span>
  <span class="timestamp"><%= time_ago_in_words(message.created_at) %></span>
  <% unless params[:edited_message].present? %>
    <span class="delete"><%= link_to image_tag("bin.png", size: "12"), message_path(message_id: message.id),
                                     method: :delete %></span>
    <% if current_user?(message.user) %>
      <span class="edit">
        <%= link_to image_tag("pencil.png", size: "12"), chat_path(edited_message: message.id,
                                                                   message_content: message.content,
                                                                   user_id: message.user_id) %>
      </span>
    <% end %>
  <% end %>
  <span class="content"><%= message.content %></span>
</li>