config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :messages
    end
  end
  resources :messages, only: [:create, :update, :destroy]
  resources :chats do
    member do
      get :members
    end
  end
  resources :chat_users, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  has_many :messages, dependent: :destroy
  has_many :chat_users, dependent: :destroy
  has_many :users, through: :chat_users

  validates :name,
            presence: true,
            length: { maximum: 50 }
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :signed_in_user
  before_action only: [:edit, :update, :show] do
    chat_member(Chat.find(params[:id]))
  end
  after_action :user_activity

  def index
    @chats = Chat.where(private: false).joins(:messages).group("chats.id").order("count(*) DESC")
                 .paginate(page: params[:page], per_page: 15)
  end

  def show
    @chat = Chat.find(params[:id])
    @members = @chat.users.paginate(page: params[:page], per_page: 10)
    @messages = Message.chat_messages_for_user(@chat, current_user)
    @message = current_user.messages.build(chat_id: @chat.id)
    @chat_user = ChatUser.find_by(chat_id: @chat.id, user_id: current_user.id)
  end

  def members
    @chat = Chat.find(params[:id])
    if !@chat.private
      @title = @chat.name
      @members = @chat.users.paginate(page: params[:page], per_page: 20)
      render 'show_members'
    else
      redirect_to chats_path
    end
  end

  def new
  end

  def create
    chat = Chat.create(name: "New Chat")
    ChatUser.create(chat_id: chat.id, user_id: current_user.id)

    if params[:user_id]
      ChatUser.create(chat_id: chat.id, user_id: params[:user_id])
    end
    redirect_to chat
  end

  def edit
    @chat = Chat.find(params[:id])
  end

  def update
    @chat = Chat.find(params[:id])
    @chat.update_attributes(chat_params)
    redirect_to @chat
  end

  private
  def chat_params
    params.require(:chat).permit(:name, :private)
  end
end

app/helpers/chats_helper.rb
module ChatsHelper

  def member?(chat)
    ChatUser.find_by(chat_id: chat.id, user_id: current_user.id)
  end

  def chat_member(chat)
    unless member? chat
      redirect_to chats_path
    end
  end

end

app/views/chats/_chat.html.erb
<li>
  <span class="content">
    <%= link_to chat.name, chat %>
    <% unless member? chat%>
      <strong id="join" class="join-btn">
        <%= button_to "Join", chat_users_path(chat_id: chat.id), class: "btn btn-primary", method: :post%>
      </strong>
    <% end %>
  </span>
  <span class="stats">
    <a href="<%= members_chat_path(chat) %>">
      <strong id="members" class="stat">
        Members: <%= chat.users.count %>
      </strong>
    </a>
      <strong id="messages" class="stat">
        Messages: <%= chat.messages.count %>
      </strong>

  </span>

</li>

app/views/chats/_chat_field.erb
<section class="chat-field">
  <% if @messages.any? %>
    <ul class="messages">
      <%= render @messages %>
    </ul>
  <% end %>
</section>

app/views/chats/_edited_message_form.html.erb
<%= form_for @message, method: :patch, url: { action: "update", controller: "messages" } do |f| %>
    <%= hidden_field_tag(:edited_message, params[:edited_message]) %>
    <%= f.text_area :content, value: params[:message_content], class: "message-form" %>
    <%= f.submit "Edit", class: "btn btn-primary input_btn" %>
<% end %>

app/views/chats/_members_list.html.erb
<h2>Members:</h2>
<% @members.each do |member| %>
  <ul>
    <div class="image">
      <%= link_to avatar_for(member, size: 30), member %>
      <% status = member.online? ? "online" : "offline" %>
      <div class="<%= status %>-mini"></div>
    </div>
    <%= link_to member.name, member %>
  </ul>
<% end %>
<%= will_paginate @members%>

app/views/chats/_message_form.html.erb
<%= form_for(@message) do |f| %>
  <%= hidden_field_tag(:chat_id, @chat.id) %>
  <%= hidden_field_tag(:user_id, current_user.id) %>
  <%= f.text_area :content, placeholder: "Write new message", class: "message-form" %>
  <%= f.submit "Input", class: "btn btn-primary input_btn" %>
<% end %>

app/views/chats/edit.html.erb
<% provide(:title, 'Edit chat') %>
<h1>Update your chat</h1>

<div class=row">
  <div class="span6 offset3">
    <%= form_for(@chat) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :private %>
        <%= f.select :private, [true, false] %>

        <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/chats/index.html.erb
<% provide(:title, 'All chats') %>
<h1>All chats</h1>

<%= will_paginate @chats%>

<ul class="chats">
  <%= render @chats %>
</ul>

<%= will_paginate @chats%>

app/views/chats/show.html.erb
<% provide(:title, @chat.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <div class="image">
          <%= avatar_for @current_user%>
          <% status = @current_user.online? ? "online" : "offline" %>
          <div class="<%= status %>-large"></div>
        </div>
        <%= @current_user.name %>
      </h1>
    </section>
    <section>
      <div class="chat-options">
        <h2>Chat options:</h2>
        <ul>
          <li><%= link_to "Edit", edit_chat_path(@chat) %></li>
          <li>
            <%= link_to "Leave", @chat_user, method: :delete,
                          data: { confirm: "Are you sure?" } %>
          </li>
        </ul>
      </div>
    </section>
    <section>
      <div class="chat-members">
        <%= render 'members_list' %>
      </div>
    </section>
  </aside>
  <div class="span8">
    <h3><span class="name"><%= @chat.name %></span></h3>
    <%= render 'chat_field' %>
    <div class="message-field">
      <% if params[:edited_message].present? %>
        <%= render 'edited_message_form' %>
      <% else %>
        <%= render 'message_form' %>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/show_members.html.erb
<% provide(:title, @title) %>
<h1><%= @title %></h1>
<h2>Members:</h2>


<%= will_paginate @members %>
<ul class="users">
  <% @members.each do |member| %>
    <li>
      <div class="image">
        <%= avatar_for member, size: 52 %>
        <% status = member.online? ? "online" : "offline" %>
        <div class="<%= status %>"></div>
      </div>
      <%= link_to member.name, member %>
    </li>
  <% end %>
</ul>
<%= will_paginate @members%>